version: "3.9"
services:
  db:
    image: timescale/timescaledb:latest-pg14
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=dev
      - POSTGRES_PASSWORD=dev
      - PGDATA=/database
      - TIMESCALEDB_TELEMETRY=off
    volumes:
      - database:/database
    restart: unless-stopped
    command: ["postgres", "-c", "log_statement=all", "-c", "log_min_messages=INFO", "-c", "log_min_error_statement=INFO", "-c", "log_min_duration_statement=0"]

volumes:
  database: {}
